services:
  app:
    image: order-system
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - postgresql_db
    environment:
      SPRING_PROFILES_ACTIVE: prod

  postgresql_db:
    image: postgres:18-alpine
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: order_system
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  adminer:
    image: adminer:standalone
    container_name: adminer
    ports:
      - "8090:8080"
    depends_on:
      - postgresql_db
volumes:
  postgres_data: